"""empty message

Revision ID: 0c34c18923e6
Revises: 3b7d061f4b5c
Create Date: 2023-09-23 18:52:56.029437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c34c18923e6"
down_revision: Union[str, None] = "3b7d061f4b5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contact",
        "repeat_interval",
        existing_type=sa.TEXT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contact",
        "repeat_interval",
        existing_type=sa.Integer(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
